apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: modelshield
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: modelshield
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: 8000
  egress:
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53